export type LabStatus = 'ready' | 'coming-soon';

export interface Lab {
    slug: string;
    title: string;
    topic: string;
    apis: string[];
    status: LabStatus;
    requiresBackend: boolean;
}

export const labs: Lab[] = [
    {
        slug: 'accessible-locators',
        title: 'Accessible Locators',
        topic: 'Roles, labels, headings, alt text, accessible names',
        apis: ['getByRole', 'getByLabel', 'getByAltText', 'getByText'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'forms-validation',
        title: 'Forms & Validation',
        topic: 'Form controls, validation messages, submit states',
        apis: ['locator.fill', 'locator.selectOption', 'locator.check', 'toHaveValue', 'toBeDisabled'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'tables-filtering',
        title: 'Tables & Filtering',
        topic: 'Search, sort, filter, pagination, row actions',
        apis: ['getByRole', 'locator.filter', 'locator.nth', 'locator.getByRole'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'async-ui',
        title: 'Async UI',
        topic: 'Loading states, retries, delayed updates',
        apis: ['toBeVisible', 'waitFor', 'expect.poll', 'toHaveText'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'network-api',
        title: 'Network & API',
        topic: 'API-backed UI, request/response interception, mock opportunities',
        apis: ['page.route', 'page.waitForResponse', 'page.waitForRequest'],
        status: 'ready',
        requiresBackend: true,
    },
    {
        slug: 'fake-auth',
        title: 'Fake Auth',
        topic: 'Login flow, protected routes, logout, session state',
        apis: ['page.goto', 'context.addCookies', 'page.evaluate', 'storageState'],
        status: 'ready',
        requiresBackend: true,
    },
    {
        slug: 'browser-events',
        title: 'Browser Events',
        topic: 'Dialogs, file uploads/downloads, navigation events',
        apis: ['page.on("dialog")', 'page.waitForEvent("download")', 'locator.setInputFiles'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'frames-contexts',
        title: 'Frames & Contexts',
        topic: 'Iframes, frame locators, isolated context concepts',
        apis: ['page.frameLocator', 'BrowserContext', 'context.newPage'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'emulation-input',
        title: 'Emulation & Input',
        topic: 'Keyboard, mouse, viewport, responsive behavior',
        apis: ['page.keyboard', 'page.mouse', 'page.setViewportSize', 'devices'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'debugging-reporting',
        title: 'Debugging & Reporting',
        topic: 'Trace viewer, screenshots, retries, timeout concepts',
        apis: ['context.tracing', 'testInfo.attach', 'test.describe.configure', 'screenshot'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'websocket-interception',
        title: 'WebSocket Interception',
        topic: 'WebSocket mocking & message interception',
        apis: ['page.routeWebSocket', 'WebSocketRoute.send', 'WebSocketRoute.onMessage'],
        status: 'ready',
        requiresBackend: true,
    },
    {
        slug: 'aria-snapshots',
        title: 'ARIA Snapshots',
        topic: 'Structural accessibility regression with toMatchAriaSnapshot',
        apis: ['expect(page).toMatchAriaSnapshot', 'accessibility tree', '/children: equal'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'clock-timers',
        title: 'Clock & Timers',
        topic: 'Controlling time with page.clock',
        apis: ['page.clock.install', 'clock.tick', 'clock.fastForward', 'clock.setFixedTime'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'api-request-context',
        title: 'API Request Context',
        topic: "Playwright's built-in HTTP client (request fixture)",
        apis: ['request.get', 'request.post', 'request.put', 'request.delete', 'APIRequestContext'],
        status: 'ready',
        requiresBackend: true,
    },
    {
        slug: 'storage-state',
        title: 'Storage State',
        topic: 'Auth state serialization & multi-user contexts',
        apis: ['context.storageState', 'browser.newContext', 'context.addCookies'],
        status: 'ready',
        requiresBackend: true,
    },
    {
        slug: 'visual-regression',
        title: 'Visual Regression',
        topic: 'Screenshot & visual diffing with toHaveScreenshot',
        apis: ['expect(page).toHaveScreenshot', 'expect(locator).toHaveScreenshot', 'maxDiffPixels'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'drag-and-drop',
        title: 'Drag & Drop',
        topic: 'Drag-and-drop, DataTransfer, and drop zones',
        apis: ['locator.dragTo', 'locator.drop', 'DataTransfer', 'dispatchEvent'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'har-recording',
        title: 'HAR Recording',
        topic: 'HAR recording, replay, and network stubs',
        apis: ['page.routeFromHAR', 'tracing.startHar', 'tracing.stopHar'],
        status: 'ready',
        requiresBackend: true,
    },
    {
        slug: 'multi-tab',
        title: 'Multi-Tab',
        topic: 'Multi-page & popup orchestration',
        apis: ['context.waitForEvent("page")', 'page.waitForEvent("popup")', 'context.pages'],
        status: 'ready',
        requiresBackend: false,
    },
    {
        slug: 'service-workers',
        title: 'Service Workers',
        topic: 'Service worker interception and offline testing',
        apis: ['serviceWorkers: "block"', 'page.route', 'context.setOffline', 'navigator.serviceWorker'],
        status: 'ready',
        requiresBackend: false,
    },
];
