export type LabStatus = 'ready' | 'coming-soon';

export interface Lab {
  slug: string;
  title: string;
  topic: string;
  apis: string[];
  status: LabStatus;
  requiresBackend: boolean;
  goal?: string;
  guidance?: string[];
  docsUrl?: string;
}

export const labs: Lab[] = [
  {
    slug: 'accessible-locators',
    title: 'Accessible Locators',
    topic: 'Roles, labels, headings, alt text, accessible names',
    apis: ['getByRole', 'getByLabel', 'getByAltText', 'getByText'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Build resilient selectors using semantic HTML attributes — roles, labels, alt text, and accessible names — so your tests stay green when styles or class names change.',
    guidance: [
      'Look at the book cards displayed on the page. How many different attributes does each card expose that you could use as a locator anchor — headings, images, buttons, status text?',
      'Some books show an "Available" badge and others show "Unavailable". Find a way to assert only on the available subset without hardcoding row indices.',
      'The genre filter buttons change which books are visible. After clicking one, how would you assert that the resulting set contains only books of that genre?',
      'Each book card has a cover image with descriptive alt text. How do you locate an element by its alt text, and what matcher confirms the image is present?',
      'The action button on each card is contextual to that book. How do you scope a locator to a specific card so you interact with the right button rather than all buttons on the page?',
      'Challenge yourself to write every locator without using CSS classes, test IDs, or XPath — rely only on the semantic APIs listed above.',
    ],
    docsUrl: 'https://playwright.dev/docs/locators',
  },
  {
    slug: 'forms-validation',
    title: 'Forms & Validation',
    topic: 'Form controls, validation messages, submit states',
    apis: ['locator.fill', 'locator.selectOption', 'locator.check', 'toHaveValue', 'toBeDisabled'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Practice interacting with every type of form control — text inputs, dropdowns, radio buttons, and checkboxes — and assert on validation error messages, field attributes, and form submission outcomes.',
    guidance: [
      'Open the page and note the initial state of the Submit button. How can you assert that a button is not yet interactive?',
      'Focus a required field, then move focus away without typing. An inline error message should appear — think about which locator strategy best targets it without relying on fragile CSS selectors.',
      'Each control type (text input, select, radio, checkbox) has a purpose-built Playwright API. Identify which one belongs to each field before writing any assertions.',
      "After interacting with a field, you may want to assert on its current value. Consider what matcher is appropriate for checking a control's selected or typed value.",
      'Fill in every required field with valid data and assert the Submit button transitions to an enabled state before you click it.',
      'Submit the form and confirm the success state appears. The confirmation region has a meaningful ARIA role — use it to write a resilient selector.',
      'For accessible fields, the DOM carries validation state as an attribute (e.g. aria-invalid). Explore how you can assert on element attributes directly rather than relying only on visible text.',
    ],
    docsUrl: 'https://playwright.dev/docs/input',
  },
  {
    slug: 'tables-filtering',
    title: 'Tables & Filtering',
    topic: 'Search, sort, filter, pagination, row actions',
    apis: ['getByRole', 'locator.filter', 'locator.nth', 'locator.getByRole'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Practice locating specific rows in a data table, applying search and filter controls in combination, asserting on sort order, and triggering per-row actions without relying on fragile position-based selectors.',
    guidance: [
      'Start by counting the visible rows before any filter is applied. Which Playwright API lets you measure the number of elements matching a locator?',
      'Type a name into the search field and assert the displayed rows update. How do you confirm each visible row contains the search term without reading every cell individually?',
      'Apply both the search filter and the department dropdown at the same time. How do you assert the intersection — only rows matching both criteria are shown?',
      'Click a sortable column header. How would you assert the first row after sorting contains the expected name, and that the last row contains the expected opposite?',
      'Navigate to a second page if pagination is present. Assert that the row content changes and that the correct page indicator is active.',
      'Each row has action buttons. How do you scope a button click to the row containing a specific employee name, rather than targeting the first button on the page?',
    ],
    docsUrl: 'https://playwright.dev/docs/locators#filter-by-text',
  },
  {
    slug: 'async-ui',
    title: 'Async UI',
    topic: 'Loading states, retries, delayed updates',
    apis: ['toBeVisible', 'waitFor', 'expect.poll', 'toHaveText'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Write reliable assertions for content that appears after a delay, values that update on a timer, and operations that may need a retry — without using arbitrary sleeps.',
    guidance: [
      'The news feed does not appear instantly. Playwright assertions automatically wait — but what is the default timeout, and how do you extend it for a specific assertion when you know the delay is longer?',
      'The loading skeleton is visible briefly before content loads. How would you assert it is present, and then that it disappears once real content replaces it?',
      'The stock price updates on a timer. How do you assert a specific value when the displayed number keeps changing? Explore the polling-based assertion API for cases where you need to keep checking until a condition is true.',
      'There is a section that can fail on the first attempt. How would you configure Playwright to retry the full test on failure, and how do retries appear in the HTML report?',
      'Think about flakiness: if your assertion fires before the UI settles, the test becomes unreliable. What strategies let you wait for a stable state — for example, waiting for a loading indicator to disappear — before making your final assertion?',
    ],
    docsUrl: 'https://playwright.dev/docs/actionability',
  },
  {
    slug: 'network-api',
    title: 'Network & API',
    topic: 'API-backed UI, request/response interception, mock opportunities',
    apis: ['page.route', 'page.waitForResponse', 'page.waitForRequest'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Practice intercepting, observing, and mocking HTTP requests that the UI makes to the backend, covering stubbed responses, request inspection, and simulated error states.',
    guidance: [
      'Open the page and watch what network requests fire during the initial load. Playwright gives you ways to wait for a specific request or response — how might you verify a particular endpoint was called?',
      'Before navigating to the page, register a route handler so you can intercept the initial data fetch and return entirely controlled data instead. Think about the relationship between when you set up the interception and when the request fires.',
      'When you intercept a request, you have several choices: block it, fulfill it with static data, or forward it to the real server and optionally modify the response. Consider which approach is appropriate for each scenario.',
      'Add a note via the UI and capture the outgoing POST request. How would you inspect the request payload to confirm the correct data was sent?',
      'Simulate a server error on one of the endpoints and verify that the UI displays an error state. What HTTP status code would cause that, and what assertion would confirm the error is shown to the user?',
      'Think about test isolation: if your test stubs the network, should it also call the real backend? Consider what side effects a real network call might introduce into a test suite.',
    ],
    docsUrl: 'https://playwright.dev/docs/network',
  },
  {
    slug: 'fake-auth',
    title: 'Fake Auth',
    topic: 'Login flow, protected routes, logout, session state',
    apis: ['page.goto', 'context.addCookies', 'page.evaluate', 'storageState'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Test the full authentication lifecycle — failed login, successful login with redirect, protected route enforcement, and logout — and explore how to avoid repeating the login flow in every test.',
    guidance: [
      'Submit the login form with wrong credentials. How do you assert the inline error message appears without relying on its CSS class?',
      'Submit with valid credentials and assert that the browser navigated to the dashboard. How do you verify the current URL after a navigation?',
      'Navigate directly to the dashboard URL without logging in first. What does the app do, and how would you assert that behavior?',
      'Log in, then click logout and assert you are returned to the login page and cannot access the dashboard anymore.',
      'If multiple tests need to start in a logged-in state, running the UI login flow in every test is slow. What does Playwright offer to serialize and reuse authenticated session state across tests?',
    ],
    docsUrl: 'https://playwright.dev/docs/auth',
  },
  {
    slug: 'browser-events',
    title: 'Browser Events',
    topic: 'Dialogs, file uploads/downloads, navigation events',
    apis: ['page.on("dialog")', 'page.waitForEvent("download")', 'locator.setInputFiles'],
    status: 'ready',
    requiresBackend: false,
    goal: "Handle native browser events that occur outside the page DOM — alert, confirm, and prompt dialogs; file uploads; and file downloads — using Playwright's event-driven APIs.",
    guidance: [
      'There are three dialog types: alert, confirm, and prompt. Each needs a handler registered on the page *before* the action that triggers it fires. What happens if you register the handler after the click?',
      'For a confirm dialog, you can either accept or dismiss. How do you tell the handler which action to take, and how do you assert the outcome reflected back on the page?',
      'For a prompt dialog, the handler can supply a return value. How would you assert the page displays the string you provided?',
      'The file upload section uses a hidden file input. How do you set files on an input element in Playwright without needing a real file picker interaction?',
      'If a download is triggered, how do you capture the download event, wait for it to complete, and assert on the file name?',
    ],
    docsUrl: 'https://playwright.dev/docs/dialogs',
  },
  {
    slug: 'frames-contexts',
    title: 'Frames & Contexts',
    topic: 'Iframes, frame locators, isolated context concepts',
    apis: ['page.frameLocator', 'BrowserContext', 'context.newPage'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Practice scoping locators inside embedded iframes and understand how browser contexts isolate cookies, storage, and session state from one another.',
    guidance: [
      'Elements inside an iframe are not reachable with a plain page locator. Which Playwright API scopes all subsequent locator calls to the content inside a specific frame?',
      'The embedded counter iframe has increment, decrement, and reset buttons. Locate the increment button inside the frame, click it several times, and assert the displayed count matches the expected value.',
      'The frame also contains a form with input fields. Fill them in and submit — think about whether the steps differ from filling a top-level page form once you have scoped to the frame.',
      'Open a second browser context from the same browser. Does it share cookies or localStorage with the first context? Write a test that explores this isolation.',
      'What is the conceptual difference between an iframe (a frame inside a page) and a browser context? When is each the right tool for test isolation?',
    ],
    docsUrl: 'https://playwright.dev/docs/frames',
  },
  {
    slug: 'emulation-input',
    title: 'Emulation & Input',
    topic: 'Keyboard, mouse, viewport, responsive behavior',
    apis: ['page.keyboard', 'page.mouse', 'page.setViewportSize', 'devices'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Practice synthesizing keyboard shortcuts, mouse movements, and viewport changes to test interactions that cannot be driven by high-level click or fill actions.',
    guidance: [
      'The command palette opens with a keyboard shortcut. How do you send a modifier+key chord in Playwright? Be precise about which API sends a combination versus individual key presses.',
      'With the palette open, use arrow keys to move the selection and Enter to confirm. Assert the correct command name appears in the result area after selection.',
      'Close the palette with the Escape key and assert it is no longer visible.',
      'There is a tooltip that appears on mouse hover. How do you move the pointer to an element to trigger a hover-dependent UI state without clicking?',
      'Resize the viewport to a narrow mobile width. How does the layout respond, and how would you assert a state that only appears on smaller screens?',
    ],
    docsUrl: 'https://playwright.dev/docs/input#keys-and-shortcuts',
  },
  {
    slug: 'debugging-reporting',
    title: 'Debugging & Reporting',
    topic: 'Trace viewer, screenshots, retries, timeout concepts',
    apis: ['context.tracing', 'testInfo.attach', 'test.describe.configure', 'screenshot'],
    status: 'ready',
    requiresBackend: false,
    goal: "Use Playwright's tracing, screenshot, and retry tooling to diagnose tests that fail intermittently or involve slow operations, and attach diagnostic artifacts to the test report.",
    guidance: [
      'The flaky button fails on every third click. Configure your test suite to retry on failure and observe how the retry count appears in the HTML report — what changes between attempts?',
      "Enable tracing only on retry using the tracing fixture. After a failure, open the saved trace in Playwright's trace viewer and identify the exact action that caused the failure.",
      "The slow operation takes two seconds to complete. How does Playwright's default timeout interact with this? How do you raise the timeout for a specific assertion when you know a step will be slow?",
      'Configure the test runner to automatically take a screenshot on failure. After triggering a failure, verify a screenshot file is saved in the test results directory.',
      'Use `testInfo.attach()` inside a test to attach extra diagnostic data — a screenshot taken at a specific step, or the current page HTML — and verify it appears in the HTML report.',
    ],
    docsUrl: 'https://playwright.dev/docs/trace-viewer-intro',
  },
  {
    slug: 'websocket-interception',
    title: 'WebSocket Interception',
    topic: 'WebSocket mocking & message interception',
    apis: ['page.routeWebSocket', 'WebSocketRoute.send', 'WebSocketRoute.onMessage'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Intercept WebSocket connections to inject server-side messages and observe client-sent messages, enabling deterministic testing of real-time UIs without relying on a live server.',
    guidance: [
      'Connect to the WebSocket server using the button. How would you assert the status indicator transitions from "connecting" to "connected"?',
      'Before navigating to the page, register a WebSocket route handler. What does this API let you do that the standard `page.route()` network interception cannot?',
      'From inside the handler, push a fabricated message to the client as if it came from the server. Assert that message appears in the chat log.',
      'Intercept a message the client sends to the server and assert that its text matches what the user typed in the input field.',
      "Consider test isolation: with a real WebSocket connection, one test's messages can bleed into another test's chat log. What does stubbing the WebSocket connection solve, and what does it sacrifice?",
    ],
    docsUrl: 'https://playwright.dev/docs/network#websocket-mocking',
  },
  {
    slug: 'aria-snapshots',
    title: 'ARIA Snapshots',
    topic: 'Structural accessibility regression with toMatchAriaSnapshot',
    apis: ['expect(page).toMatchAriaSnapshot', 'accessibility tree', '/children: equal'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Assert the structural shape of the accessibility tree to catch semantic regressions — changed heading levels, missing landmarks, reordered list items — that pixel screenshots cannot detect.',
    guidance: [
      'Run `expect(locator).toMatchAriaSnapshot()` against the accordion in its default (all-collapsed) state. On first run Playwright generates a baseline — read it and understand what each YAML line represents.',
      'Expand one accordion section and capture the snapshot again. How does the tree change? Explore what the `/children: equal` constraint does to matching strictness.',
      'The multi-step wizard shows which step is current and which are completed. Assert the stepper\'s tree structure — consider which ARIA attributes drive the "current" and "completed" states.',
      'Modify your snapshot template to use a flexible regex match for a value that may vary, while keeping the structural hierarchy strict. How do partial-match patterns differ from exact strings in the YAML template?',
      'Intentionally change a heading level in DevTools and re-run the test. How does the snapshot diff report the regression? How do you update a stored snapshot when an intentional UI change is made?',
    ],
    docsUrl: 'https://playwright.dev/docs/aria-snapshots',
  },
  {
    slug: 'clock-timers',
    title: 'Clock & Timers',
    topic: 'Controlling time with page.clock',
    apis: ['page.clock.install', 'clock.tick', 'clock.fastForward', 'clock.setFixedTime'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Control the browser clock to test time-dependent UI — countdowns, scheduled toasts, and session expiry warnings — without waiting for real time to pass.',
    guidance: [
      'Install the fake clock before navigating to the page. What is the difference between `page.clock.install()` and `page.clock.setFixedTime()`? Which one lets you advance time programmatically?',
      'Start the countdown timer and advance the fake clock by a known amount. Assert the displayed time reflects exactly that elapsed duration without any real waiting.',
      'The session expiry toast appears after a delay. Advance the clock to the moment the toast should appear and assert it becomes visible — then advance past its expiry time and assert the final expired state.',
      'Advance the clock in small steps and assert intermediate states on the way — for example, the countdown value at 30 seconds remaining. This verifies the UI updates correctly at each tick.',
      'Consider: if you advance the clock by a large amount all at once using `fastForward`, do all intermediate `setInterval` callbacks fire? Verify your understanding by checking whether skipped states are reflected.',
    ],
    docsUrl: 'https://playwright.dev/docs/clock',
  },
  {
    slug: 'api-request-context',
    title: 'API Request Context',
    topic: "Playwright's built-in HTTP client (request fixture)",
    apis: ['request.get', 'request.post', 'request.put', 'request.delete', 'APIRequestContext'],
    status: 'ready',
    requiresBackend: true,
    goal: "Use Playwright's built-in HTTP client to call your backend directly in test setup and teardown — seeding data before a test and cleaning up after — without touching the browser UI.",
    guidance: [
      'The `request` fixture gives you an HTTP client that operates outside the browser. Make a GET request to `/api/tasks` and assert on the response status and body shape — no `page.goto()` needed.',
      'In a `beforeEach` hook, use `request.post()` to create a known task before the test navigates to the page. This guarantees predictable seed data without relying on prior UI interactions.',
      'After a test that creates a task through the UI, use `request.delete()` in `afterEach` to remove it — keeping the server state clean between test runs.',
      'Write a test that only uses the `request` fixture with no browser page at all. Assert the full API contract: create a task, update it, and delete it — verifying each step through the response.',
      'Consider the difference between using the `request` fixture and calling `page.evaluate(() => fetch(...))` from inside the browser. When would you choose each approach?',
    ],
    docsUrl: 'https://playwright.dev/docs/api-testing',
  },
  {
    slug: 'storage-state',
    title: 'Storage State',
    topic: 'Auth state serialization & multi-user contexts',
    apis: ['context.storageState', 'browser.newContext', 'context.addCookies'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Serialize authenticated session state to a file so tests can start pre-logged-in without repeating the UI login flow, and run parallel scenarios for different user roles in isolated contexts.',
    guidance: [
      'After logging in through the UI (or via the API), call `context.storageState({ path })` to save the session to a file. Open the file and explore what it contains — what data makes the server trust this session?',
      'Load the saved state into a fresh browser context with `browser.newContext({ storageState })`. Navigate to the profile page and assert the correct user is displayed — no login step needed.',
      'The page shows different content for admin and regular users. Create two separate storage state files — one per role — and write tests that load each one and assert role-specific UI.',
      'Use the `request` fixture (without a browser) to authenticate as each user and capture their storage state. This avoids a full browser startup just for the setup step.',
      'Think about where storage state files should live in a CI pipeline: should they be committed, generated at test runtime, or cached? What happens if they expire?',
    ],
    docsUrl: 'https://playwright.dev/docs/auth',
  },
  {
    slug: 'visual-regression',
    title: 'Visual Regression',
    topic: 'Screenshot & visual diffing with toHaveScreenshot',
    apis: ['expect(page).toHaveScreenshot', 'expect(locator).toHaveScreenshot', 'maxDiffPixels'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Take and compare pixel-level screenshots of page regions to catch unintended visual changes, and handle dynamic content areas that would otherwise cause false failures.',
    guidance: [
      'Take a full-page screenshot baseline with `expect(page).toHaveScreenshot()`. On the first run Playwright creates the baseline file — subsequent runs compare against it. Where is the file stored?',
      'Scope a screenshot to an individual section using `expect(locator).toHaveScreenshot()`. The button showcase and color palette sections are stable candidates — how do you locate each section?',
      'If a section contains a value that changes between runs (a live timestamp or a counter), use the `mask` option to exclude that region from the comparison. How do you supply a locator as a mask?',
      "Intentionally change a button's background color in DevTools and rerun the test. Observe the diff output — what information does Playwright provide about the pixel difference?",
      'Explore the `maxDiffPixels` and `maxDiffPixelRatio` threshold options. When would a ratio be more useful than an absolute pixel count?',
    ],
    docsUrl: 'https://playwright.dev/docs/screenshots',
  },
  {
    slug: 'drag-and-drop',
    title: 'Drag & Drop',
    topic: 'Drag-and-drop, DataTransfer, and drop zones',
    apis: ['locator.dragTo', 'locator.drop', 'DataTransfer', 'dispatchEvent'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Trigger drag-and-drop interactions and assert on the resulting layout — from high-level convenience APIs down to low-level mouse event simulation when needed.',
    guidance: [
      'Use `locator.dragTo(target)` to drag a Kanban card from one column to another. Assert the card is now in the target column and no longer in the source column.',
      'Not all drag implementations respond to the high-level API — some require dispatching raw mouse events. If `dragTo` does not produce the expected result, explore how to simulate a drag using sequential mouse down, move, and up calls.',
      'After a drag, assert the card counts in both columns changed as expected: the source column should have one fewer card, the target one more.',
      'The sortable list lets you reorder items within the same container. How would you assert the new item order after dragging one item above another?',
      'Consider: if a card has both a drag handle and other interactive children (buttons, links), how do you ensure your drag targets the handle specifically?',
    ],
    docsUrl: 'https://playwright.dev/docs/input#drag-and-drop',
  },
  {
    slug: 'har-recording',
    title: 'HAR Recording',
    topic: 'HAR recording, replay, and network stubs',
    apis: ['page.routeFromHAR', 'tracing.startHar', 'tracing.stopHar'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Record a real network session into a HAR file and replay it in tests so the full request/response history is served from the file instead of hitting a live server.',
    guidance: [
      'Record a HAR by passing `{ update: true }` to `page.routeFromHAR()` before navigating. This saves every response to the file rather than replaying from it. Navigate to the page and stop recording.',
      'In a second test, call `page.routeFromHAR()` without `{ update }` to enter replay mode. Navigate to the page and assert the product list renders with the data you recorded.',
      'Combine HAR replay with `page.route()` to override a single endpoint with a mock response while all other requests are served from the HAR. What does the precedence between the two look like?',
      'Think about when HAR replay is more useful than manually written mocks: HAR captures real response headers, cookies, and timing — mocks give you full control. When would you choose each approach?',
      'HAR files can be committed to source control as test fixtures. What kinds of UI changes would require re-recording the HAR, and which ones would not?',
    ],
    docsUrl: 'https://playwright.dev/docs/network#record-and-replay-requests',
  },
  {
    slug: 'multi-tab',
    title: 'Multi-Tab',
    topic: 'Multi-page & popup orchestration',
    apis: ['context.waitForEvent("page")', 'page.waitForEvent("popup")', 'context.pages'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Capture and interact with pages opened in new browser tabs and popup windows, and understand how multiple pages within the same browser context share state.',
    guidance: [
      'When a button opens a new tab, Playwright must capture the new page object. You need to set up the event listener *before* clicking — why does the order matter, and what pattern ensures you never miss the event?',
      'Once you have the new page reference, interact with it like any other page. Navigate, locate a heading, assert its text, then close the tab.',
      'The second button opens a popup window (not a tab). How does the event you listen for differ from the new-tab case, and what is the API difference?',
      'The page has a section about shared state between tabs in the same context. Write to localStorage in one page and read it from a second page — does the value appear?',
      'Think about test cleanup: if a test opens extra pages and does not close them, what could go wrong in subsequent tests that run in the same context?',
    ],
    docsUrl: 'https://playwright.dev/docs/pages',
  },
  {
    slug: 'service-workers',
    title: 'Service Workers',
    topic: 'Service worker interception and offline testing',
    apis: [
      'serviceWorkers: "block"',
      'page.route',
      'context.setOffline',
      'navigator.serviceWorker',
    ],
    status: 'ready',
    requiresBackend: false,
    goal: "Understand how service workers intercept network requests before Playwright's routing layer, and practice both blocking them entirely and routing through them intentionally.",
    guidance: [
      'Register the service worker using the button, then fetch the items. Notice the response source changes. How would you assert whether data came from the service worker cache versus the real network?',
      'Create a browser context with the service worker blocking option enabled. Navigate to the same page and use `page.route()` to intercept a request — does it work now? What does this tell you about interception order?',
      'Without blocking service workers, try registering a `page.route()` handler for the same request the service worker intercepts. Which one takes precedence, and how can you verify it?',
      'Use `context.setOffline(true)` to take the context offline while the service worker is active. What does the UI show? Now do the same with the service worker blocked — does the result differ?',
      'Consider when you would *not* want to block service workers: if you are specifically testing the caching strategy or offline behavior, the service worker must be active. How would you structure those tests differently from the rest of the suite?',
    ],
    docsUrl: 'https://playwright.dev/docs/service-workers-experimental',
  },
  {
    slug: 'geolocation-permissions',
    title: 'Geolocation & Permissions',
    topic: 'Browser permission grants, geolocation, clipboard',
    apis: ['context.grantPermissions', 'context.setGeolocation', 'context.clearPermissions'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Grant, deny, and clear browser permissions in tests — geolocation for a café finder and clipboard for a share-link flow — and assert both the granted and denied UI states.',
    guidance: [
      'Call `context.grantPermissions(["geolocation"])` and `context.setGeolocation({ latitude, longitude })` before clicking "Find Cafés Near Me". What order must these calls happen in relative to the navigation?',
      'The café list only renders after position resolves. How do you assert that a list item is visible when it appears asynchronously after a permission grant?',
      'To test the denial path, do NOT call `grantPermissions`. The browser will block the geolocation request by default in Playwright. Assert the `role="alert"` error message appears.',
      'Grant the `"clipboard-read"` and `"clipboard-write"` permissions before exercising the clipboard panel. What single Playwright API lets you grant multiple permissions at once?',
      'After copying, assert the success status message appears. Then click "Paste" and assert the pasted URL is visible in the read-only input.',
      "Use `context.clearPermissions()` between tests to avoid one test's grants leaking into the next. Why is this especially important for permission-sensitive tests?",
      'Think about the difference between `context.grantPermissions()` and a real user granting permissions via the browser permission prompt. What user-facing prompt does `grantPermissions` bypass?',
    ],
    docsUrl:
      'https://playwright.dev/docs/api/class-browsercontext#browser-context-grant-permissions',
  },
  {
    slug: 'locator-handlers',
    title: 'Locator Handlers',
    topic: 'Auto-dismiss overlays with addLocatorHandler',
    apis: ['page.addLocatorHandler', 'page.removeLocatorHandler', 'LocatorHandlerOptions'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Register handlers that automatically dismiss overlays (cookie banners, modals, survey dialogs) the moment they appear, so your test flow is never blocked by unexpected interruptions.',
    guidance: [
      'Register a `page.addLocatorHandler()` for the cookie-consent banner before navigating. The handler fires automatically whenever the overlay becomes visible — you do not need to poll for it manually.',
      'With the "Force overlays every step" toggle on, an overlay appears on every Next click. Assert you can still complete all three checkout steps without the handler missing any overlay.',
      'Call `page.removeLocatorHandler(locator)` after step 2, then proceed to step 3. What happens when an overlay fires without a handler? Assert the test observes that the overlay is blocking.',
      'Handlers accept an `{ times }` option. Register a handler with `{ times: 1 }` and verify it fires exactly once then stops auto-dismissing on subsequent occurrences.',
      'Each overlay type has a distinct ARIA role: the cookie banner uses `role="dialog"`, and the session survey uses `role="alertdialog"`. Which role implies a more urgent interruption, and how does that affect expected user behaviour?',
      'Think about test-suite design: should every test register handlers for every possible overlay, or should tests that specifically validate overlay behaviour leave handlers unregistered?',
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-page#page-add-locator-handler',
  },
  {
    slug: 'media-locale',
    title: 'Media & Locale Emulation',
    topic: 'CSS media emulation, locale, timezone',
    apis: ['page.emulateMedia', 'colorScheme', 'reducedMotion', 'context locale/timezoneId'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Override CSS media features and browser locale at the context and page level to test dark mode, reduced-motion, print layout, and locale-sensitive date/currency formatting without changing system settings.',
    guidance: [
      'Call `page.emulateMedia({ colorScheme: "dark" })` and assert the colour-scheme label updates to "Dark". How does this differ from adding a CSS class to the `<html>` element?',
      'Emulate `colorScheme: "light"` and assert the label flips back. Notice the component uses `window.matchMedia` — not a React state variable — so only real media emulation will change it.',
      'Call `page.emulateMedia({ reducedMotion: "reduce" })` and assert the motion panel shows "Reduced". Switch to `"no-preference"` and assert the label returns to "Motion on".',
      'Call `page.emulateMedia({ media: "print" })` and assert the print banner becomes visible. This exercises CSS `@media print` rules without needing a real print dialog.',
      'Create a browser context with `{ locale: "de-DE", timezoneId: "Europe/Berlin" }`. Navigate to the lab and assert the date panel displays a German-formatted date and a euro-formatted currency string.',
      'Confirm that changing the locale at the context level affects the `Intl.DateTimeFormat` output without any hardcoded locale string in the component. How does Playwright propagate the locale to the browser?',
    ],
    docsUrl: 'https://playwright.dev/docs/emulation#color-scheme-and-media',
  },
  {
    slug: 'scroll-lazy-loading',
    title: 'Scroll & Lazy Loading',
    topic: 'Infinite scroll, IntersectionObserver, viewport assertions',
    apis: ['locator.scrollIntoViewIfNeeded', 'expect(locator).toBeInViewport', 'page.route'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Test an infinite-scroll feed driven by IntersectionObserver — assert that new items load as the sentinel enters the viewport, that a specific item can be scrolled into view, and that page.route can stub the paginated endpoint.',
    guidance: [
      "After the page loads, assert the first 8 feed items are visible. Playwright's auto-waiting handles the initial fetch — you just need to assert the rendered rows.",
      'The feed loads more items when a sentinel element at the bottom enters the viewport. How do you scroll to the bottom of the list in a way that triggers the IntersectionObserver?',
      'After scrolling, assert that items from page 2 are now visible. How do you confirm a specific item by its title text?',
      'Keep scrolling until the "You\'re all caught up" end marker appears. Assert it is visible to confirm all pages have been fetched.',
      'Use `locator.scrollIntoViewIfNeeded()` to bring a specific item (e.g. item #30) into view, then assert `expect(locator).toBeInViewport()` passes.',
      'Use `page.route("/api/feed*", ...)` to stub the endpoint with controlled data. Assert only your stubbed items appear — this lets you test the infinite-scroll logic without a running backend.',
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed',
  },
  {
    slug: 'accessibility-scanning',
    title: 'Accessibility Scanning',
    topic: 'Automated axe-core scans with @axe-core/playwright',
    apis: ['AxeBuilder({ page }).analyze()', 'results.violations', '.include()', '.withTags()'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Run automated accessibility scans with axe-core, assert on violations and their counts, scope scans to specific page regions, and filter by WCAG tag — then watch the violation count drop to zero after toggling to accessible controls.',
    guidance: [
      'Import `AxeBuilder` from `@axe-core/playwright` and call `.analyze()` on the broken form state. How do you assert that the results contain at least one violation?',
      'Each entry in `results.violations` has an `id`, `impact`, and `nodes` array. Log a violation to understand its shape — which fields would you include in a failure message to make the bug easy to diagnose?',
      'Toggle the page to the accessible state and run the scan again. Assert `results.violations` is an empty array. What specific fixes caused the violation count to reach zero?',
      'Use `.include("#form-region")` to scope the scan to only the form section. How does a scoped scan differ from a full-page scan in terms of what it can and cannot catch?',
      'Use `.withTags(["wcag2a", "wcag2aa"])` to filter the scan to only WCAG 2.x rules. Why might you want a tag-filtered scan rather than running every axe rule?',
      'Think about where automated scanning fits in a broader accessibility strategy: what categories of a11y issues can axe-core reliably detect, and which require manual testing or assistive technology review?',
    ],
    docsUrl: 'https://playwright.dev/docs/accessibility-testing',
  },
  {
    slug: 'shadow-dom',
    title: 'Shadow DOM & Web Components',
    topic: 'Piercing shadow roots, custom elements, declarative shadow DOM',
    apis: ['getByRole', 'locator', 'getByText', 'locator.evaluate'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Discover that Playwright locators automatically pierce open shadow roots, and practise interacting with native custom elements — a star-rating widget and a labelled input — that attach their own shadow trees.',
    guidance: [
      'The star-rating widget is a custom element with an open shadow root. Try `getByRole("radio")` without any extra configuration — does Playwright find the stars inside the shadow DOM?',
      'The labelled input custom element wraps a native `<input>` inside its shadow root. Use `getByLabel` to find it by its visible label text. Does the label association work across the shadow boundary?',
      'After clicking a star, the widget reflects the chosen rating as `aria-checked="true"` on that radio. How would you assert which star is currently selected without reaching into implementation details?',
      'The rating widget also exposes a `value` attribute on the host element itself. Use `locator.evaluate` to read a DOM property from the custom element host and assert its value matches the star you clicked.',
      'Use `getByText` to locate a piece of text that lives inside a shadow root. Does it behave the same as locating text in a regular DOM node?',
      'Think about the limits: Playwright pierces *open* shadow roots automatically. What would you need to do differently for a *closed* shadow root, and why are closed roots rarely the right choice for testability?',
    ],
    docsUrl: 'https://playwright.dev/docs/locators#locate-in-shadow-dom',
  },
  {
    slug: 'touch-gestures',
    title: 'Touch & Mobile Gestures',
    topic: 'tap, touchscreen, hasTouch, swipe, device descriptors',
    apis: ['page.tap', 'locator.tap', 'page.touchscreen', 'hasTouch', 'devices'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Test touch-only interactions — tapping buttons, swiping a carousel, and asserting touch-driven UI states — using the Playwright touchscreen API and device descriptors.',
    guidance: [
      'The tap counter only increments on `touch` events, not `click`. Use `locator.tap()` to send a touch tap and assert the count increases.',
      'Try clicking the tap counter with `locator.click()` instead. The count should not change — this distinguishes tap events from mouse clicks on this element.',
      'The swipe carousel advances its slide when you perform a horizontal touch swipe. Use `page.touchscreen.tap` to send a raw touch, or consider `page.touchscreen` combined with `pointerdown`/`pointermove`/`pointerup` events via `page.dispatchEvent` to simulate a swipe.',
      'Assert the active slide indicator updates after a swipe. Which Playwright assertion confirms the correct slide is now visible?',
      'Launch a browser context configured as a mobile device using `devices["iPhone 15"]`. Does the `navigator.maxTouchPoints` value differ from a desktop context? How can `page.evaluate` help you inspect it?',
      'Think about when `hasTouch: true` matters: if a page uses `window.matchMedia("(pointer: coarse)")` to enable a mobile UI, how does the device descriptor affect which code path runs?',
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-touchscreen',
  },
  {
    slug: 'init-scripts',
    title: 'Init Scripts & Seeding',
    topic: 'page.addInitScript, context.addInitScript, pre-load injection',
    apis: ['page.addInitScript', 'context.addInitScript'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Use `page.addInitScript()` and `context.addInitScript()` to inject code that runs before the page loads — stubbing globals for determinism, seeding localStorage to skip onboarding, and injecting feature flags.',
    guidance: [
      'The page reads `window.__FLAGS__` immediately on load and shows a banner when the `betaFeature` flag is `true`. Use `page.addInitScript` to inject the flags object *before* navigation and assert the banner is visible.',
      'The lucky number widget calls `Math.random()` on load. Stub `Math.random` inside an `addInitScript` to always return `0.42` and assert the displayed number equals `42` (the stub value × 100, rounded).',
      'The onboarding modal appears unless `localStorage.getItem("onboarded")` equals `"true"`. Use `addInitScript` to seed localStorage so the modal never appears — then assert it is not present.',
      'Try the same localStorage seed with `context.addInitScript` instead of `page.addInitScript`. Navigate to the page in a fresh page object from the same context — does the seed persist?',
      'The init script runs *before* page scripts. What would happen if you tried to set localStorage *after* `page.goto` instead? Test the difference.',
      'Think about order of execution: if you call `page.addInitScript` multiple times, in which order do the scripts run? What does that mean for scripts that depend on each other?',
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-page#page-add-init-script',
  },
  {
    slug: 'server-sent-events',
    title: 'Server-Sent Events',
    topic: 'EventSource, SSE streaming, route interception, progressive DOM',
    apis: ['page.route', 'page.waitForResponse', 'expect.poll', 'toContainText'],
    status: 'ready',
    requiresBackend: true,
    goal: 'Assert on progressively-appended DOM updates from a live SSE stream, then stub the stream with `page.route()` to deliver controlled events and test the UI deterministically.',
    guidance: [
      'Click "Start Stream" and watch log entries appear one by one. Use `expect.poll` to wait until at least three entries are visible — why is polling the right choice here instead of a single `toBeVisible`?',
      'Each SSE event type (info, warn, error) renders with a different colour badge. After the stream delivers a "warn" event, assert the corresponding badge text is visible in the log.',
      'Use `page.waitForResponse` to capture the `/api/sse` response object before navigating. How do you confirm the response has `Content-Type: text/event-stream`?',
      'Use `page.route("/api/sse", ...)` to intercept the stream and fulfill it with a hand-crafted SSE payload (two or three events). Assert exactly those entries appear in the log — no more.',
      'Click "Stop Stream" while events are still arriving. Assert the log stops growing: call `page.waitForTimeout(500)` and then assert the entry count is the same as before.',
      'Think about test isolation: a real SSE connection keeps a TCP socket open. If your test navigates away before closing the stream, what cleanup is needed so the connection does not leak between tests?',
    ],
    docsUrl: 'https://playwright.dev/docs/network',
  },
  {
    slug: 'soft-assertions',
    title: 'Soft Assertions & Test Steps',
    topic: 'expect.soft, expect.poll, toPass, test.step, annotations',
    apis: ['expect.soft', 'expect.poll', 'expect(...).toPass', 'test.step'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Use soft assertions to collect multiple independent failures in one test run, wrap retry-until-pass logic in `expect.poll` / `toPass`, and group actions into named `test.step` blocks for readable traces.',
    guidance: [
      'The profile dashboard has four independent widgets. Write a test that uses `expect.soft` for each widget assertion — observe that a failure in one widget does not abort the test and all four are checked.',
      'The activity score widget updates on a short timer. Use `expect.poll` to keep re-reading the score until it reaches the expected value. How does poll differ from a single `toBeVisible` with a long timeout?',
      'The status badge animates before settling on a final value. Use `expect(locator).toPass({ timeout: 3000 })` to retry the assertion block until it passes. When is `toPass` more appropriate than `expect.poll`?',
      'Wrap each widget check in a `test.step("Check <widget>", async () => {...})`. Open the HTML report or trace viewer — how do the steps appear, and how does naming them help you pinpoint a failure?',
      'Add a `test.info().annotations.push({ type: "issue", description: "DASH-42" })` call inside a step. Verify the annotation appears on the test result in the HTML report.',
      'Run the test with intentional soft-assertion failures. How many failures are reported? Where in the output do soft failures appear relative to the test completion message?',
    ],
    docsUrl: 'https://playwright.dev/docs/test-assertions#soft-assertions',
  },
  {
    slug: 'passkey-authentication',
    title: 'Passkey Authentication',
    topic: 'WebAuthn passkey registration and sign-in with a CDP virtual authenticator',
    apis: [
      'context.newCDPSession',
      'WebAuthn.addVirtualAuthenticator',
      'navigator.credentials.create',
      'navigator.credentials.get',
    ],
    status: 'ready',
    requiresBackend: true,
    goal: 'Register and sign in with a WebAuthn passkey, driving the full credential ceremony in tests with a CDP-backed virtual authenticator instead of a physical security key or OS prompt.',
    guidance: [
      'Before clicking "Register passkey", attach a CDP virtual authenticator via `page.context().newCDPSession(page)` and `WebAuthn.addVirtualAuthenticator`. What happens if you click the button before the authenticator is attached?',
      'The authenticator is configured with `hasResidentKey: true` and `hasUserVerification: true`. What do these two authenticator properties represent, and why does this registration flow depend on both?',
      "After registering, sign in with the passkey. Assert the browser navigates to the dashboard and shows the registered user's name.",
      'Sign out and assert you are returned to the registration screen. Visit the dashboard URL directly without a session — what happens?',
      'The CDP `WebAuthn` domain emits events like `credentialAdded` when `navigator.credentials.create()` succeeds. How could you assert on that event instead of, or in addition to, the UI state?',
      "Consider: unlike the Fake Auth lab's username/password fixture, there is no password to guess or intercept. What security properties does a passkey ceremony give you that a plaintext credential POST cannot?",
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-cdpsession',
  },
  {
    slug: 'client-storage-partitioning',
    title: 'Web Storage & Partitioned Cookies',
    topic: 'localStorage/sessionStorage scoping and CHIPS-style partitioned cookies',
    apis: ['context.addCookies', 'context.cookies', 'context.newPage', 'page.reload'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Explore how localStorage, sessionStorage, and partitioned cookies differ in scope and lifetime, and use context-level cookie APIs to set and inspect a CHIPS-style partitioned cookie without a real cross-site setup.',
    guidance: [
      'Toggle the theme preference a few times, then reload the page with `page.reload()`. Assert the value survives — it is persisted in `localStorage`, which is scoped per browser context, not per navigation.',
      'Write a draft note, then open a second page in the same browser context with `context.newPage()`. Does the draft note appear there? `sessionStorage` is scoped to a single top-level browsing context, not shared across tabs the way `localStorage` is.',
      'Before navigating, use `context.addCookies([{ name: "widget_partitioned", value: "1", ... }])` to set a cookie ahead of time. What does a `partitionKey` option represent, and why might a third-party embedded widget need its cookie partitioned by top-level site?',
      'Navigate to the page without pre-setting the cookie and assert the widget shows its locked state. Then call `context.addCookies()` mid-test and click "Re-check cookie" — does the widget unlock without a page reload? What does that tell you about when `document.cookie` reflects newly added cookies?',
      'Use `context.cookies()` to read back the cookies in the current context and assert the `widget_partitioned` cookie is present with the value you set.',
      'Explore whether `context.clearCookies()` affects localStorage or sessionStorage too. Which Playwright API would you reach for to clear storage rather than just cookies?',
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies',
  },
  {
    slug: 'console-runtime-diagnostics',
    title: 'Console & Runtime Diagnostics',
    topic: 'Capturing console messages, uncaught errors, and outgoing requests during a test',
    apis: ["page.on('console')", "page.on('pageerror')", "page.on('request')", 'expect.poll'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Capture console output, uncaught runtime errors, and outgoing network requests as they happen during a test, instead of relying only on trace viewer screenshots after a failure.',
    guidance: [
      "Register a `page.on('console', ...)` listener before clicking any button. Trigger the info, warning, and error log actions and assert each `consoleMessage.text()` was captured with the matching `consoleMessage.type()`.",
      'Trigger "Throw uncaught error" and assert it via a `page.on(\'pageerror\', ...)` listener rather than the action log — what does the error message look like compared to a console.error() call?',
      'Trigger "Reject a promise" with the same `pageerror` listener attached. Does an unhandled promise rejection show up the same way an uncaught synchronous throw does? Verify your assumption rather than guessing.',
      'Use `page.waitForRequest()` to capture the outgoing request fired by "Fetch a missing resource" before clicking the button. Why does the listener need to be registered first?',
      "Check your current Playwright version's docs for `page`-level accessor methods that return the *history* of console messages, errors, or requests for the page's lifetime, as an alternative to manually collecting them in local arrays via event listeners.",
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-page#page-event-console',
  },
  {
    slug: 'dom-memory-diagnostics',
    title: 'Memory & DOM Leak Diagnostics',
    topic: 'Detecting retained DOM nodes with page.requestGC and node-count assertions',
    apis: ['page.requestGC', 'page.evaluate', 'expect.poll', 'locator.count'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Detect a realistic "dismissed but never released" DOM node leak by counting retained nodes before and after forcing garbage collection, and understand why requestGC() alone cannot fix a leak.',
    guidance: [
      'Click "Spawn 50 toasts" and wait for them to auto-dismiss (about 1.5 s each). Assert the graveyard count reaches 50 — the toasts are visually gone from the active list, but their nodes are still retained elsewhere.',
      'Call `page.requestGC()` right after the toasts dismiss, before clicking "Clear leaked nodes". Does the graveyard count change? What does this tell you about the difference between a node being *reachable* and a node being *garbage*?',
      'Click "Clear leaked nodes" and assert the graveyard count returns to 0. This is the actual fix — removing the last reference to the nodes, not calling `requestGC()`.',
      'Spawn another batch and, before they dismiss, assert the active-toast count matches how many you spawned. Then wait and assert it drops back to 0 as they move to the graveyard.',
      'Think about how you would find this kind of bug in a real app without a dedicated graveyard counter: what `document.querySelectorAll("*").length` assertion, taken before and after a repeated mount/unmount cycle, could catch an unbounded node leak?',
    ],
    docsUrl: 'https://playwright.dev/docs/api/class-page',
  },
  {
    slug: 'custom-assertions',
    title: 'Custom Assertions & Matcher Composition',
    topic: 'Authoring domain-specific matchers with expect.extend, mergeExpects, and mergeTests',
    apis: ['expect.extend', 'mergeExpects', 'mergeTests'],
    status: 'ready',
    requiresBackend: false,
    goal: 'Author your own domain-specific Playwright matchers with expect.extend() — for a valid price, an order status, and beyond — and compose them across files with mergeExpects() and mergeTests().',
    guidance: [
      'The order price, status badge, and star rating are plain elements with `data-testid` and ARIA attributes — nothing enforces that the price text is actually a valid, positive currency value. Write a custom matcher with `expect.extend()` that parses the text and fails if it is not.',
      "A custom matcher receives the *value* being asserted on — for a Playwright locator, you will need to `await locator.textContent()` (or another locator method) inside the matcher before you can validate it. Why can Playwright matchers be async when many other assertion libraries' custom matchers are not?",
      'Return `{ pass, message }` from your matcher. Deliberately make it fail once and read the failure message Playwright prints — how does it differ from the default `toHaveText` failure output?',
      'Write a second custom matcher, `toHaveOrderStatus(expected)`, that checks the `data-status` attribute rather than the visible badge text. Which is more resilient to a copy change in the label?',
      'If you split matchers across two files — one for pricing, one for order status — how would `mergeExpects()` combine them into a single `expect` your test file imports? Try it.',
      'Explore `mergeTests()` for combining fixtures from two modules the same way `mergeExpects()` combines matchers. When would a project need both?',
    ],
    docsUrl: 'https://playwright.dev/docs/test-assertions#add-custom-matchers-using-expectextend',
  },
];
